server:
  port: 9000

logging:
  file:
    path: /spring/log
  pattern:
    file: "%d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} ==== %msg%n"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/calmdiary?serverTimezone=GMT%2B8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    username: princebah@163.com
    password: OXDVNPISBCFHCIPB
    host: smtp.163.com
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: Javen #可以任意
    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: princebah@163.com #与上面的username保持一致
debug: true

